

theme: minima

header_pages:
  - page-one.md

site.author: Adolfo Ramírez Corona
site.email: "adolforamirez@gmail.com"
  

twitter_username: adolforismos
github_username: adolforismos
instagram_username: adolforamirez
keybase_username: adolforismos
youtube_username: AdolfoRamírezCorona
youtube_channel: UCdnijz8hqfio0kvnnYKQLyQ
youtube_channel_name: Adolfo Ramírez Corona
