

theme: minima

header_pages:
  - page-one.md

author: "Adolfo Ramírez Corona"
email: "adolforamirez@gmail.com"
  
medium_username: adolforismos
twitter_username: adolforismos
github_username: adolforismos
instagram_username: adolforamirez
keybase_username: adolforismos
youtube_username: AdolfoRamírezCorona
youtube_channel: UCdnijz8hqfio0kvnnYKQLyQ
youtube_channel_name: Adolfo Ramírez Corona
