
  

theme: minima
# https://github.com/jekyll/minima/tree/2.5-stable

header_pages:
  - none
title: adolforismos' working notes
author: "Adolfo Ramírez Corona"
email: "adolforamirez@gmail.com"
  
medium_username: adolforismos
twitter_username: adolforismos
# github_username: adolforismos
# instagram_username: adolforamirez
# keybase_username: adolforismos
# youtube_username: AdolfoRamírezCorona
# youtube_channel: UCdnijz8hqfio0kvnnYKQLyQ
# youtube_channel_name: Adolfo Ramírez Corona

 plugins:
  - jekyll-feed
