

theme: minima

header_pages:
  - page-one.md

site.author.name: Adolfo Ramírez Corona
site.author.email: "adolforamirez@gmail.com"
  
minima.social_links:
  twitter: adolforismos
  github: adolforismos
  instagram: adolforamirez
  keybase: adolforismos
  youtube: AdolfoRamírezCorona
  youtube_channel: UCdnijz8hqfio0kvnnYKQLyQ
  youtube_channel_name: Adolfo Ramírez Corona
